#pragma once

#include <string>

#include "AnimEngine.h"   // BounceType, used by the easing presets below

// Parameter naming. Per-stage parameters are generated by suffixing a stage
// index, so the plugin code and the overlay can both address them without a
// hand-maintained table of 50-odd string literals.

namespace mtx {

// --- Global ---
constexpr const char* kParamStageCount     = "stageCount";
constexpr const char* kParamActiveStage    = "activeStage";   ///< which stage the overlay edits
constexpr const char* kParamEditTarget     = "editTarget";    ///< 0 = From, 1 = To
constexpr const char* kParamShowCurve      = "showCurveEditor";
constexpr const char* kParamShowLibrary    = "showCurveLibrary";
constexpr const char* kParamShowTimeline   = "showTimeline";
constexpr const char* kParamShowPath       = "showMotionPath";
constexpr const char* kParamShowOpacity    = "showOpacitySlider";

/// Set while a gizmo drag is in progress, so the renderer draws a faded copy of
/// the source at the pose being dragged. Hidden and **not persistent**: it is a
/// momentary interface state, and one that must never survive into a project
/// file or an export.
constexpr const char* kParamPreviewGhost   = "previewGhost";

/// Whether the drag preview happens at all. A real setting, saved with the
/// project, unlike the momentary flag above.
constexpr const char* kParamDragPreview    = "dragPreviewEnabled";

// Note: there is deliberately no timing-version parameter. An earlier design
// gated the absolute-to-clip-relative conversion on one, which failed badly --
// asked before the clip was attached the host reported a placeholder clip
// start, so the conversion did nothing and then stamped itself complete,
// locking the effect out permanently. Legacy values are recognised by magnitude
// on every read instead (see LooksTimelineAbsolute), which is self-correcting
// and needs no flag.
constexpr const char* kParamFilter         = "filterMode";
constexpr const char* kParamEdge           = "edgeMode";

// --- Base transform: a static resting pose, applied under the animation ---
constexpr const char* kParamGroupBase      = "grpBase";
constexpr const char* kParamBaseScale      = "baseScale";
constexpr const char* kParamBaseScaleY     = "baseScaleY";
constexpr const char* kParamBaseLinkScale  = "baseLinkScale";
constexpr const char* kParamBasePos        = "basePos";
constexpr const char* kParamBaseRot        = "baseRot";
constexpr const char* kParamBaseTiltX      = "baseTiltX";
constexpr const char* kParamBaseSwivelY    = "baseSwivelY";
constexpr const char* kParamBaseOpacity    = "baseOpacity";
constexpr const char* kParamBaseAnchor     = "baseAnchor";
constexpr const char* kParamBaseReset      = "baseReset";

// --- Presets ---
constexpr const char* kParamGroupPresets   = "grpPresets";
constexpr const char* kParamSaveEffect     = "savePresetEffect";
constexpr const char* kParamSaveStage      = "savePresetStage";
constexpr const char* kParamLoadPreset     = "loadPreset";
constexpr const char* kParamLoadPresetFit  = "loadPresetFit";

/// Trigger for the overlay's LOAD button. A push button cannot be pressed
/// programmatically in OFX, so the overlay flips this boolean instead and
/// changedParam treats the flip as the press. Hidden and non-persistent: it is
/// a message, not a setting.
constexpr const char* kParamLoadFromOverlay = "loadPresetFromOverlay";
constexpr const char* kParamPresetFolder   = "presetFolderPath";   ///< read-out only
constexpr const char* kParamSetFolder      = "setPresetFolder";
constexpr const char* kParamResetFolder    = "resetPresetFolder";

// --- Motion blur ---
constexpr const char* kParamBlurEnabled    = "motionBlur";
constexpr const char* kParamShutterAngle   = "shutterAngle";
constexpr const char* kParamShutterPhase   = "shutterPhase";
constexpr const char* kParamBlurSamples    = "blurSamples";
constexpr const char* kParamBlurAdaptive   = "blurAdaptive";

// --- Overlay state, grouped so it stays out of the way ---
constexpr const char* kParamGroupOverlay   = "grpOverlay";

// --- Per stage (suffixed with 1-based index) ---
// Every section is a collapsible group.
//
// An earlier version used label-type string parameters as plain dividers
// instead, to avoid a wall of disclosure arrows. Two things killed that: the
// panel roughly tripled in size as base transforms, presets, motion paths and
// bounce controls arrived, and the label dividers turned out to render in
// Fusion but not in Resolve -- the text sits in the parameter's *value* while
// Resolve draws the (empty) label, so the separators were invisible in the very
// host this is written for. A group header is drawn by the host itself, so it
// cannot go missing that way.
constexpr const char* kParamGroupTiming    = "grpTiming";
constexpr const char* kParamGroupFrom      = "grpFrom";
constexpr const char* kParamGroupTo        = "grpTo";
constexpr const char* kParamGroupEasing    = "grpEasing";
constexpr const char* kParamCurveName      = "curveName";
constexpr const char* kParamSaveCurve      = "saveCurve";
constexpr const char* kParamGroupPath      = "grpPath";
constexpr const char* kParamEnabled        = "enabled";
constexpr const char* kParamAnchor2        = "timingAnchor";   ///< TimingAnchor
constexpr const char* kParamStartFrame     = "startFrame";
constexpr const char* kParamEndFrame       = "endFrame";
constexpr const char* kParamSetStart       = "setStart";
constexpr const char* kParamSetEnd         = "setEnd";
constexpr const char* kParamSyncPeak       = "syncPeakToPlayhead";
constexpr const char* kParamSyncPeakEase   = "syncPeakByEasing";
constexpr const char* kParamSyncPeakFromOverlay = "syncPeakFromOverlay";
constexpr const char* kParamSyncEaseFromOverlay = "syncEaseFromOverlay";
constexpr const char* kParamDuration       = "duration";   ///< derived, display only
constexpr const char* kParamLinkScale      = "linkScale";
constexpr const char* kParamScaleFrom      = "scaleFrom";
constexpr const char* kParamScaleTo        = "scaleTo";
constexpr const char* kParamScaleYFrom     = "scaleYFrom";
constexpr const char* kParamScaleYTo       = "scaleYTo";
constexpr const char* kParamTiltXFrom      = "tiltXFrom";
constexpr const char* kParamTiltXTo        = "tiltXTo";
constexpr const char* kParamSwivelYFrom    = "swivelYFrom";
constexpr const char* kParamSwivelYTo      = "swivelYTo";
constexpr const char* kParamPosFrom        = "posFrom";
constexpr const char* kParamPosTo          = "posTo";
constexpr const char* kParamRotFrom        = "rotFrom";
constexpr const char* kParamRotTo          = "rotTo";
constexpr const char* kParamOpacityFrom    = "opacityFrom";
constexpr const char* kParamOpacityTo      = "opacityTo";
// --- Quick Control ---
//
// Eight one-shot actions behind a dropdown and a single Apply, instead of eight
// push buttons stacked at the top of the Inspector.
//
// The panel has no columns to spread them across: the only column mechanism OFX
// offers is page-based (kOfxParamPageSkipColumn), and Resolve reports
// maxPages = 0, so every parameter is one full-width row. Eight rows of buttons
// pushed the controls that are actually adjusted -- poses, timing, easing --
// most of a screen down the panel. Two rows is the whole point.
//
// Choice-plus-Apply rather than a choice that fires on selection, because these
// overwrite work: picking Flatten by mistake while scrolling a dropdown should
// not destroy four stages.
constexpr const char* kParamQuickAction     = "quickAction";
constexpr const char* kParamQuickApply      = "quickApply";

/// Overlay's QUICK panel. The overlay writes kParamQuickAction and then flips
/// this, so the choice parameter doubles as the argument and one trigger serves
/// all eight actions. See kParamLoadFromOverlay for why a boolean, not a button.
constexpr const char* kParamQuickFromOverlay = "quickFromOverlay";

/// Whether the overlay's Quick Control panel is up. Hidden and not persisted:
/// an open panel is a momentary state, and one left showing across a project
/// reload would be sitting over the picture for no reason anybody remembers.
constexpr const char* kParamShowQuick        = "showQuickPanel";

/** Quick Control dropdown order, grouped by what a given action touches:
 *  the two ends of a stage, then the stage, then the whole effect. */
enum QuickAction
{
    kQuickCopyFromTo  = 0,   ///< FROM pose -> TO pose, active stage
    kQuickCopyToFrom  = 1,
    kQuickSwapEnds    = 2,
    kQuickCopyStage   = 3,
    kQuickPasteStage  = 4,
    kQuickFlatten     = 5,
    kQuickCopyEffect  = 6,
    kQuickPasteEffect = 7,
    kQuickActionCount = 8
};

/** @brief Dropdown label for a QuickAction, also used for the overlay's rows. */
inline const char* QuickActionLabel(int action)
{
    switch (action)
    {
        case kQuickCopyFromTo:  return "Copy A to B";
        case kQuickCopyToFrom:  return "Copy B to A";
        case kQuickSwapEnds:    return "Swap A and B";
        case kQuickCopyStage:   return "Copy Stage";
        case kQuickPasteStage:  return "Paste Stage";
        case kQuickFlatten:     return "Flatten to Stage 1";
        case kQuickCopyEffect:  return "Copy All Settings";
        case kQuickPasteEffect: return "Paste All Settings";
        default:                return "";
    }
}

constexpr const char* kParamAnchor         = "anchor";
constexpr const char* kParamPathC1         = "pathC1";      ///< offset of the first path handle
constexpr const char* kParamPathC2         = "pathC2";      ///< offset of the second
constexpr const char* kParamPathReset      = "pathReset";
constexpr const char* kParamEasingPreset   = "easingPreset";
constexpr const char* kParamEaseIn         = "easeIn";
constexpr const char* kParamEaseOut        = "easeOut";
constexpr const char* kParamAnticipation   = "anticipation";
constexpr const char* kParamOvershoot      = "overshoot";
constexpr const char* kParamBounceType     = "bounceType";
constexpr const char* kParamBounceAmount   = "bounceAmount";
constexpr const char* kParamBounceCount    = "bounceCount";
constexpr const char* kParamBounceDamping  = "bounceDamping";
constexpr const char* kParamBounceStart    = "bounceStart";

/** @brief Per-stage parameter name, e.g. StageParam("scaleFrom", 0) -> "scaleFrom1". */
inline std::string StageParam(const char* base, int stageIndex)
{
    return std::string(base) + std::to_string(stageIndex + 1);
}

/** Easing preset dropdown order. Custom must be last: selecting a preset stamps
 *  the four amount parameters, and touching any of them flips back to Custom. */
enum EasingPreset
{
    kEasingLinear     = 0,
    kEasingSmooth     = 1,
    kEasingEaseIn     = 2,
    kEasingEaseOut    = 3,
    kEasingOvershoot  = 4,
    kEasingSpring     = 5,
    kEasingBounce     = 6,
    kEasingCustom     = 7
};

/** @brief The easing amounts a preset stamps out.
 *  Values are percentages (except bounceCount), matching the parameter ranges. */
struct EasingPresetValues
{
    float easeIn, easeOut, anticipation, overshoot;
    int   bounceType;
    float bounceAmount, bounceCount, bounceDamping, bounceStart;
};

inline EasingPresetValues PresetValues(int preset)
{
    switch (preset)
    {
        //                     in     out   antic  over   type            amt    count  damp  start
        case kEasingLinear:    return {  0.0f,  0.0f, 0.0f,  0.0f, kBounceNone,    0.0f, 3.0f, 50.0f, 55.0f };
        case kEasingSmooth:    return { 42.0f, 42.0f, 0.0f,  0.0f, kBounceNone,    0.0f, 3.0f, 50.0f, 55.0f };
        case kEasingEaseIn:    return { 42.0f,  0.0f, 0.0f,  0.0f, kBounceNone,    0.0f, 3.0f, 50.0f, 55.0f };
        case kEasingEaseOut:   return {  0.0f, 42.0f, 0.0f,  0.0f, kBounceNone,    0.0f, 3.0f, 50.0f, 55.0f };
        case kEasingOvershoot: return {  0.0f, 32.0f, 0.0f, 80.0f, kBounceNone,    0.0f, 3.0f, 50.0f, 55.0f };

        // Spring lands around two thirds of the way in and rings out over the
        // remainder, which reads as a settle rather than a wobble.
        case kEasingSpring:    return {  0.0f, 30.0f, 0.0f,  0.0f, kBounceSpring, 35.0f, 3.0f, 45.0f, 60.0f };

        // A ball bounce lands earlier, because the rebounds themselves are the
        // interesting part and need room.
        case kEasingBounce:    return { 20.0f,  0.0f, 0.0f,  0.0f, kBounceBall,   55.0f, 4.0f, 35.0f, 45.0f };

        default:               return { 42.0f, 42.0f, 0.0f,  0.0f, kBounceNone,    0.0f, 3.0f, 50.0f, 55.0f };
    }
}

} // namespace mtx
