#pragma once

#include <string>

// Parameter naming. Per-stage parameters are generated by suffixing a stage
// index, so the plugin code and the overlay can both address them without a
// hand-maintained table of 50-odd string literals.

namespace mtx {

// --- Global ---
constexpr const char* kParamStageCount     = "stageCount";
constexpr const char* kParamActiveStage    = "activeStage";   ///< which stage the overlay edits
constexpr const char* kParamEditTarget     = "editTarget";    ///< 0 = From, 1 = To
constexpr const char* kParamFilter         = "filterMode";
constexpr const char* kParamEdge           = "edgeMode";

// --- Motion blur ---
constexpr const char* kParamBlurEnabled    = "motionBlur";
constexpr const char* kParamShutterAngle   = "shutterAngle";
constexpr const char* kParamShutterPhase   = "shutterPhase";
constexpr const char* kParamBlurSamples    = "blurSamples";
constexpr const char* kParamBlurAdaptive   = "blurAdaptive";

// --- Per stage (suffixed with 1-based index) ---
// Section headings are label-type string parameters, not groups: they divide
// the controls visually without adding another collapsible section to click
// through. Only the active stage's parameters are visible at a time.
constexpr const char* kParamLabelTiming    = "lblTiming";
constexpr const char* kParamLabelFrom      = "lblFrom";
constexpr const char* kParamLabelTo        = "lblTo";
constexpr const char* kParamLabelEasing    = "lblEasing";
constexpr const char* kParamEnabled        = "enabled";
constexpr const char* kParamStartFrame     = "startFrame";
constexpr const char* kParamEndFrame       = "endFrame";
constexpr const char* kParamSetStart       = "setStart";
constexpr const char* kParamSetEnd         = "setEnd";
constexpr const char* kParamDuration       = "duration";   ///< derived, display only
constexpr const char* kParamScaleFrom      = "scaleFrom";
constexpr const char* kParamScaleTo        = "scaleTo";
constexpr const char* kParamPosFrom        = "posFrom";
constexpr const char* kParamPosTo          = "posTo";
constexpr const char* kParamRotFrom        = "rotFrom";
constexpr const char* kParamRotTo          = "rotTo";
constexpr const char* kParamOpacityFrom    = "opacityFrom";
constexpr const char* kParamOpacityTo      = "opacityTo";
constexpr const char* kParamAnchor         = "anchor";
constexpr const char* kParamEasingPreset   = "easingPreset";
constexpr const char* kParamEaseIn         = "easeIn";
constexpr const char* kParamEaseOut        = "easeOut";
constexpr const char* kParamAnticipation   = "anticipation";
constexpr const char* kParamOvershoot      = "overshoot";

/** @brief Per-stage parameter name, e.g. StageParam("scaleFrom", 0) -> "scaleFrom1". */
inline std::string StageParam(const char* base, int stageIndex)
{
    return std::string(base) + std::to_string(stageIndex + 1);
}

/** Easing preset dropdown order. Custom must be last: selecting a preset stamps
 *  the four amount parameters, and touching any of them flips back to Custom. */
enum EasingPreset
{
    kEasingLinear     = 0,
    kEasingSmooth     = 1,
    kEasingEaseIn     = 2,
    kEasingEaseOut    = 3,
    kEasingOvershoot  = 4,
    kEasingCustom     = 5
};

/** @brief The four easing amounts a preset stamps out.
 *  Values are percentages, matching the parameter ranges. */
struct EasingPresetValues { float easeIn, easeOut, anticipation, overshoot; };

inline EasingPresetValues PresetValues(int preset)
{
    switch (preset)
    {
        case kEasingLinear:    return {  0.0f,  0.0f, 0.0f,  0.0f };
        case kEasingSmooth:    return { 42.0f, 42.0f, 0.0f,  0.0f };  // CSS ease-in-out
        case kEasingEaseIn:    return { 42.0f,  0.0f, 0.0f,  0.0f };  // CSS ease-in
        case kEasingEaseOut:   return {  0.0f, 42.0f, 0.0f,  0.0f };  // CSS ease-out
        case kEasingOvershoot: return {  0.0f, 32.0f, 0.0f, 80.0f };
        default:               return { 42.0f, 42.0f, 0.0f,  0.0f };
    }
}

} // namespace mtx
